version: '3.9'

services:
  app:
    build: .
    container_name: myapp1
    restart: always
    ports: 
      - "3000:3000"
    env_file:
      - .env

  app2:
    build: .
    container_name: myapp2
    restart: always
    ports: 
      - "3001:3000"
    env_file:
      - .env

  app3:
    build: .
    container_name: myapp3
    restart: always
    ports: 
      - "3002:3000"
    env_file:
      - .env